services:
  app-db:
    image: mysql:8.0
    container_name: mysql_card_db
    restart: always
    environment:
      MYSQL_DATABASE: card_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: