server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: card-api

spring:
  application:
    name: card-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 1000
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  datasource:
    url: jdbc:mysql://localhost:3306/card_db?useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: user
    password: user_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    job.enabled: false
    jdbc:
      initialize-schema: always

  threads:
    virtual:
      enabled: true
api:
  security:
    secret-key: test123
    token:
      secret: d6d0921284fc2b291c80797aa18d9cb8f59629516af1300ef72c69be6ba3941d
      expiration: 3600000

logging:
  level:
    com.hyperativa.card_api: DEBUG
    org.springframework.security: DEBUG
